# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    always_authenticate_before_granting: true

    encoders:
        App\Entity\User\User: bcyrpt


    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username


    role_hierarchy:
        ROLE_IT: [ROLE_ADMIN, ROLE_TEACHER, ROLE_HW, ROLE_IT_TEACHER]
        ROLE_ADMIN: ROLE_IT
        ROLE_HW: ROLE_TEACHER
        ROLE_IT_TEACHER: ROLE_TEACHER
        ROLE_TEACHER: ROLE_USER


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            logout:
                path:  security_logout
            form_login:
                login_path:           security_login
                provider:             fos_userbundle
                #provider:             chain_provider
                check_path:           security_login
                csrf_token_generator: security.csrf.token_manager


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logs, roles: ROLE_HW }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/(_(profiler|wdt|error))/, roles: ROLE_IT}
