twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
      ['bootstrap_4_layout.html.twig']
    globals:
        locales: '%locales%'
        application_log_level: '%application_log_level%'
        application_hotline: '%application_hotline%'
        application_admin_email: '%application_admin_email%'
        application_sender_email: '%application_sender_email%'
        application_receiver_email: '%application_receiver_email%'
        application_group_it: '%application_group_it%'
        application_group_caretaker: '%application_group_caretaker%'
        application_group_teacher: '%application_group_teacher%'
        application_group_teacher_it: '%application_group_teacher_it%'
        mailer_transport: '%mailer_transport%'
        mailer_host: '%mailer_host%'
        mailer_user: '%mailer_user%'
        mailer_password: '%mailer_password%'
        webuntis_enable: '%webuntis_enable%'
        webuntis_school: '%webuntis_school%'
        webuntis_username: '%webuntis_username%'
        webuntis_password: '%webuntis_password%'
        webuntis_api_client: '%webuntis_api_client%'
        eventghost_port: '%eventghost_port%'
        eventghost_username: '%eventghost_username%'
        eventghost_password: '%eventghost_password%'
        eventghost_websocket_server: '%eventghost_websocket_server%'
        eventghost_websocket_ssl: '%eventghost_websocket_ssl%'
        eventghost_websocket_port: '%eventghost_websocket_port%'
        eventghost_websocket_ssl_port: '%eventghost_websocket_ssl_port%'
        ldap_host: '%ldap_host%'
        ldap_username: '%ldap_username%'
        ldap_password: '%ldap_password%'
        ldap_use_ssl: '%ldap_use_ssl%'
        ldap_allow_empty_password: '%ldap_allow_empty_password%'
        ldap_account_domain_name: '%ldap_account_domain_name%'
        ldap_account_domain_name_short: '%ldap_account_domain_name_short%'
        ldap_base_dn: '%ldap_base_dn%'
        ldap_filter: '%ldap_filter%'
        firebase_server_id: '%firebase_server_id%'
        firebase_server_key: '%firebase_server_key%'
