extends: google
parserOptions:
  ecmaVersion: 6
  sourceType: "module"
  allowImportExportEverywhere: true
rules:
  no-invalid-this: 0
  indent: ["error", 2]
  no-unused-vars: 1
  space-before-function-paren: 0
  no-multi-spaces: 0
  key-spacing: 0
  max-len: 0
