imports:
    - { resource: application.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BCCCronManagerBundle/Resources/config/assetic.yml" }

parameters:
    locale: de

web_profiler:
    toolbar: true
    intercept_redirects: false

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource:        "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:
        enabled:         true
    templating:
        engines:         ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:      ~
    fragments:       ~
    http_method_override: true
    ide: "phpstorm://open?file=%%f&line=%%l"
    profiler:
        matcher:
            service: app.admin_matcher

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'
    globals:
        app_twig_helper: '@app.twig_helper'
        settings_handler: '@app.settings_handler'
    cache: false
    auto_reload: true

doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

assetic:
    bundle: 'AppBundle'
    filters:
        uglifyjs2:
            bin: "%kernel.root_dir%/../bin/node_modules/uglify-js/bin/uglifyjs"
            compress: true
        uglifycss:
            bin: "%kernel.root_dir%/../bin/node_modules/uglifycss/uglifycss"
            ugly_comments: true
    assets:
        glyphicons-ttf:
            inputs: '%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/glyphicons-halflings-regular.ttf'
        glyphicons-woff:
            inputs: '%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        glyphicons-woff2:
            inputs: '%kernel.root_dir%/../web/assets/vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

gos_web_socket:
    pushers:
        wamp:
            host: 127.0.0.1
            port: "%eventghost_websocket_port%"
    server:
        port: "%eventghost_websocket_port%"        #The port the socket server will listen on
        host: 127.0.0.1
        router:
            resources:
                - "@AppBundle/Resources/config/pubsub/routing.yml"

fr3d_ldap:
    driver:
        host: "%ldap_host%"
        username: "%ldap_username%"
        password: "%ldap_password%"
        useSsl: "%ldap_use_ssl%"
        allowEmptyPassword: "%ldap_allow_empty_password%"
        useStartTls: false
        accountDomainName: "%ldap_account_domain_name%"
        accountDomainNameShort: "%ldap_account_domain_name_short%"
    user:
        baseDn: "%ldap_base_dn%"
        filter: "%ldap_filter%"
        usernameAttribute: samaccountname
        attributes:
            - { ldap_attr: samaccountname, user_method: setUsername }
            - { ldap_attr: mail, user_method: setEmail }
            - { ldap_attr: memberof, user_method: setLdapGroups }
            - { ldap_attr: givenname, user_method: setFirstName }
            - { ldap_attr: sn, user_method: setLastName }

fos_user:
    db_driver: orm
    from_email:
        address: "%application_admin_email%"
        sender_name: System
    firewall_name: main
    user_class: AppBundle\Entity\User
    group:
        group_class: AppBundle\Entity\Group

fresh_firebase_cloud_messaging:
    sender_id: "%firebase_server_id%"
    server_key: "%firebase_server_key%"
