# http://symfony.com/doc/current/book/security.html
security:

    always_authenticate_before_granting: true

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]
        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        AppBundle\Entity\User: bcrypt


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            fr3d_ldap:  ~
            logout:
                path: /logout
            form_login:
                provider: chain_provider
                login_path: /login
                check_path: /login_check

    role_hierarchy:
        ROLE_IT: [ROLE_ADMIN, ROLE_TEACHER, ROLE_HW, ROLE_IT_TEACHER]
        ROLE_ADMIN: ROLE_IT
        ROLE_HW: ROLE_TEACHER
        ROLE_IT_TEACHER: ROLE_TEACHER
        ROLE_TEACHER: ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logs, roles: ROLE_HW }
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/(_(profiler|wdt|error))/, roles: ROLE_IT}
