# http://symfony.com/doc/current/book/service_container.html
services:
    fos_user.doctrine_registry:
        alias: doctrine

    user_listener:
        class: AppBundle\EventListener\UserEventListener
        arguments: ['%application_group_it%', '%application_group_caretaker%', '%application_group_teacher%', '%application_group_teacher_it%']
        calls:
            - [ setLogger, ['@logger'] ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    user_settings_listener:
        class: AppBundle\EventListener\UserSettingsListener
        tags:
            - name: doctrine.event_listener
              event: prePersist

    app.usage_logger.authentication_success_listener:
        class: AppBundle\EventListener\UsageLogger
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - name: kernel.event_listener
              event: security.interactive_login
              method: onAuthenticationSuccess
            - name: kernel.event_listener
              event: app.command_event
              method: onCommandEvent

    app.command.topic_service:
        class: AppBundle\Topic\CommandTopic
        tags:
            - { name: gos_web_socket.topic }

    app.webuntis.handler:
        class: AppBundle\Service\WebUntisHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%webuntis_school%'
            - '%webuntis_username%'
            - '%webuntis_password%'
            - '%webuntis_api_client%'
        tags:
            - name: kernel.event_listener
              event: kernel.response
              method: onKernelResponse

    app.log.level_listener:
        class: AppBundle\EventListener\LogListener
        arguments:
            - '%application_log_level%'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.observation.command_listener:
        class: AppBundle\EventListener\ObservationListener
        arguments:
            - '@gos_web_socket.wamp.pusher'
        tags:
            - name: kernel.event_listener
              event: app.command_event
              method: onCommandEvent

    app.observation.zulu_change_listener:
        class: AppBundle\EventListener\ZuluLockListener
        arguments: ['@gos_web_socket.wamp.pusher', '@service_container']
        tags:
            - name: doctrine.event_listener
              event: postUpdate
            - name: kernel.event_listener
              event: kernel.response
              method: onKernelResponse

    app.status.fetcher:
        class: AppBundle\Service\StatusFetcher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@command_handler'
            - '%kernel.root_dir%'

    app.twig_helper:
        class: AppBundle\Service\TwigHelper
        arguments:
            - '@doctrine.orm.entity_manager'

    app.settings_handler:
        class: AppBundle\Service\SettingsHandler
        arguments:
            - '@kernel'

    app.admin_matcher:
        class: AppBundle\Profiler\AdminMatcher
        arguments:
            - '@security.authorization_checker'
        public: false

    command_handler:
        class: AppBundle\Service\CommandsHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@validator'
            - '%eventghost_port%'
            - '%eventghost_username%'
            - '%eventghost_password%'

    # Override profiler
    data_collector.twig:
        class: Symfony\Bridge\Twig\DataCollector\TwigDataCollector
        tags:
           - { name: 'data_collector', priority: '0' }
        arguments: ['@twig.profile']

    gos_web_socket.data_collector:
        class: Gos\Bundle\WebSocketBundle\DataCollector\WebsocketDataCollector
        tags:
            - name: data_collector
              priority: '0'
