# http://symfony.com/doc/current/book/service_container.html
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../../src/*'
        exclude: '../../src/{DependencyInjection,Entity,Form/Listener,Migrations,Tests,Kernel.php}'

    fos_user.doctrine_registry:
        alias: doctrine

    user_listener:
        class: App\EventListener\UserEventListener
        arguments: ['%application_group_it%', '%application_group_caretaker%', '%application_group_teacher%', '%application_group_teacher_it%']
        calls:
            - [ setLogger, ['@logger'] ]
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    user_settings_listener:
        class: App\EventListener\UserSettingsListener
        tags:
            - name: doctrine.event_listener
              event: prePersist

    app.usage_logger.authentication_success_listener:
        class: App\EventListener\UsageLogger
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - name: kernel.event_listener
              event: security.interactive_login
              method: onAuthenticationSuccess
            - name: kernel.event_listener
              event: app.command_event
              method: onCommandEvent

    app.command.topic_service:
        class: App\Topic\CommandTopic
        tags:
            - { name: gos_web_socket.topic }

    app.webuntis.handler:
        class: App\Service\WebUntisHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%webuntis_school%'
            - '%webuntis_username%'
            - '%webuntis_password%'
            - '%webuntis_api_client%'
        tags:
            - name: kernel.event_listener
              event: kernel.response
              method: onKernelResponse

    app.log.level_listener:
        class: App\EventListener\LogListener
        arguments:
            - '%application_log_level%'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.observation.command_listener:
        class: App\EventListener\ObservationListener
        arguments:
            - '@gos_web_socket.wamp.pusher'
        tags:
            - name: kernel.event_listener
              event: app.command_event
              method: onCommandEvent

    app.observation.zulu_change_listener:
        class: App\EventListener\ZuluLockListener
        arguments: ['@gos_web_socket.wamp.pusher', '@service_container']
        tags:
            - name: doctrine.event_listener
              event: postUpdate
            - name: kernel.event_listener
              event: kernel.response
              method: onKernelResponse

    app.status.fetcher:
        class: App\Service\StatusFetcher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%kernel.root_dir%'

    app.twig_helper:
        class: App\Service\TwigHelper
        arguments:
            - '@doctrine.orm.entity_manager'

    app.settings_handler:
        class: App\Service\SettingsHandler
        arguments:
            - '@kernel'

    command_handler:
        class: App\Service\CommandsHandler
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@validator'
            - '%eventghost_port%'
            - '%eventghost_username%'
            - '%eventghost_password%'
