' @ipa
@startuml

title Aktivitätsdiagramm - Befehle

(*) --> "Anfrage trifft auf AppController"

partition AppController.php {

    "Anfrage trifft auf AppController" --> "Funktion commandsAction wird ausgeführt"

    partition AppController::commandsAction {
        "Funktion commandsAction wird ausgeführt"                           --> "EntityManager wird erstellt"
        "EntityManager wird erstellt"                                       --> "CommandsHandler wird erstellt"
        "CommandsHandler wird erstellt"                                     --> "Der EntityManager durchsucht die Datenbank\nnach dem Befehl"
        if "Command wurde gefunden" then
            -down->[Ja] "EventDispatcher wird erstellt"
            "EventDispatcher wird erstellt"                                     --> "Ein neues CommandEvent wird erstellt"
            "Ein neues CommandEvent wird erstellt"                              --> "Der Benutzer und der Command wird gesetzt"
            "Der Benutzer und der Command wird gesetzt"                         --> "Der EventDispatcher dispatcht das Event\nan 'app.command_event'"
            "Der EventDispatcher dispatcht das Event\nan 'app.command_event'"   --> ===Event===
            ===Event===                                                         --> "Der Befehl wird vom CommandHandler ausgeführt"
            if "Command ist ein ZuluCommand" then
                -left->[Ja] "Hol der Status der Zulu"
                "Hol der Status der Zulu"                                           --> "Ein JSON string wird für die Antwort erstellt"
            else
                -down->[Nein] "Ein JSON string wird für die Antwort erstellt"
            endif
            "Ein JSON string wird für die Antwort erstellt"                         --> "Der JSON-Header wird in der Response gesetzt."
            }
            'AppController::commandsAction
            }
            'AppController.php
            "Der JSON-Header wird in der Response gesetzt." --> ===Response===
        }
        'AppController::commandsAction
        }
        'AppController.php
        else
            -right->[Nein] "Exception wird geworfen.\n'Dieser Befehl existiert nicht.'"
            "Exception wird geworfen.\n'Dieser Befehl existiert nicht.'"        --> ===Response===
        endif
    }
    'AppController::commandsAction
}
'AppController.php

===Response=== -->[Antwort wird gesendet] (*)


partition Observer.php {
    ===Event=== -->[Observer hört auf Event] "Event wird gehört"
    partition Observer::onCommandEvent {
        "Event wird gehört"                                                                                     --> "Funktion onCommandEvent wird ausgeführt"
        "Funktion onCommandEvent wird ausgeführt"                                                               --> "Zulu des Benutzers wird aus der Datenbank geholt"
        "Zulu des Benutzers wird aus der Datenbank geholt"                                                      --> "Der WebSocket-Pusher pusht den Command\nund den Status der Zulu über WebSocket\nan die Observierer"
        "Der WebSocket-Pusher pusht den Command\nund den Status der Zulu über WebSocket\nan die Observierer"    --> ===Event===
    }
}



@enduml