@startuml
skinparam backgroundColor #FFF
skinparam usecase {
	BackgroundColor #3F51B5
	BorderColor #3F51B5

	ActorBackgroundColor #3F51B5
	ActorBorderColor #3F51B5
	ActorFontColor #000
	ActorFontName Roboto
	ActorFontSize 17

    ParticipantBorderColor #3F51B5
    ParticipantBackgroundColor #3F51B5
    ParticipantFontColor #FFF
    ParticipantFontName Roboto
    ParticipantFontSize 17
}

left to right direction

:Informatik: as it
:Hausdienst: as hw
:Lehrer:     as teacher

rectangle Webserver {
    rectangle Steuerung {
        teacher -> (Klassenzimmer)
        hw -> (Klassenzimmer)
        it -> (Klassenzimmer)
    }
    rectangle "Logs und Observation" {
        hw -> (Auswertungen)
        it -> (Auswertungen)
    }
    rectangle "Systemeinstellungen" {
        it -> (LDAP-Einstellungen)
        it -> (CRON Jobs)
    }
}

rectangle Zulu {
    (Klassenzimmer) -> (Beamer 1)
    (Klassenzimmer) -> (Beamer 2)
    (Klassenzimmer) -> (Visualizer)
    (Klassenzimmer) -> (Audioinputs)
    (Klassenzimmer) -> (Videoinputs)
}

rectangle "EventGhost (IPA)" #yellow {
    (Klassenzimmer) -> (VLC)
    (Klassenzimmer) -> (Windows Media Player)
    (Klassenzimmer) -> (PowerPoint)
}

center footer Dieses Diagramm wurde im Rahmen der IPA von Dominik Müller 2017 erstellt.

@enduml