' @ipa
@startuml
!include base.puml

title Kommunikationsablauf - EventGhost (Beispiel PowerPoint)

actor "Informatik"      as it
actor "Lehrer/Dozent"   as teacher
participant "Webserver" as server
participant "Schul-PC"  as pc

|||
== Anfrage des Lehrers ==
|||

teacher -> server:      "Nächste PowerPoint-Folie"
activate server

server --> server:      Authentifizierung,\nAutorisierung,\nLogging, etc.

server -> it:           "Lehrer XYZ möchte PowerPoint-Folie wechseln"
note left:              Via WebSocket\nPubSub

|||
== REST-Request an Schul-PC und Antwort and Lehrer ==
|||

server ->o pc:          REST-API Anfrage.
activate pc
server -> teacher:      "Anfrage wurde gestellt"
destroy server

pc --> pc:              EventGhost mapping\nzu Python-Script
pc --> pc:              Python-Script\nwird ausgeführt
destroy pc
@enduml
