' @ipa
@startuml
!include base.puml

title Kommunikationsablauf - LDAP-Authentifikation

actor "Benutzer"        as user
participant "Webserver" as server
participant "Directory" as dc

|||
== Login Anfrage ==
|||

group Verwaltungsnetz oder WLAN
    user -> server:             Anfrage auf ""/login_check""\nBenutzername, Passwort\nund CSRF-Token.
    activate server
    note left:                  HTTPS
end group

server --> server:              Validierung des CSRF-Tokens.

|||
== LDAP-Authentifizierung ==
|||

group Server-Netz
    server -> dc:               LDAP-Directory wird durchsucht.
    activate dc
    note left:                  LDAP
    dc -> server:               Resultat wird zurückgegeben.
    destroy dc
end group

server --> server:              Mapping der LDAP-Properties\nzu Funktionen, wenn Benutzer\nnoch nicht existent war.\nDefinition in ""ldap_config.yml""

server --> server:              Vor Antwort an Benutzer, LDAP-Gruppen\ndes Benutzer-Objektes, werden\nauf Gruppen in der Applikation\ngemapt.

|||
== Antwort und Weiterleitung ==
|||

group Verwaltungsnetz oder WLAN
    server -> user:             Wenn erfolgreich authentifiziert.\nWeiterleiten auf ""/"".\n\nSonst "Benutzername/Passwort\nfalsch"
    destroy server
    note left:                  HTTPS
end grouo


@enduml
